# Generated by Django 3.2.5 on 2022-04-12 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_ticker', models.CharField(max_length=255)),
                ('type_name', models.CharField(max_length=255)),
                ('solar_system', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installer_name', models.CharField(max_length=255)),
                ('activity_id', models.IntegerField(null=True)),
                ('blueprint', models.CharField(max_length=255)),
                ('blueprint_id', models.BigIntegerField(null=True)),
                ('blueprint_type_id', models.BigIntegerField(null=True)),
                ('completed_character_id', models.IntegerField(null=True)),
                ('completed_data', models.DateTimeField(null=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=13, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('installer_id', models.IntegerField(null=True)),
                ('job_id', models.IntegerField(null=True)),
                ('licensed_runs', models.IntegerField(null=True)),
                ('pause_date', models.DateTimeField(null=True)),
                ('probability', models.FloatField(null=True)),
                ('product_type_id', models.IntegerField(null=True)),
                ('runs', models.IntegerField(null=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('station_id', models.BigIntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('paused', 'Paused'), ('ready', 'Ready'), ('reverted', 'Reverted')], max_length=10)),
                ('successful_runs', models.IntegerField(null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esi.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indsutry_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
