# Generated by Django 3.2.5 on 2021-11-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi', '0002_rename_industryjobs_industryjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryjob',
            name='probability',
            field=models.FloatField(null=True),
        ),
    ]
