# Generated by Django 3.2.5 on 2021-10-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_entryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(help_text='This is the grey text', max_length=200),
        ),
    ]
