# Generated by Django 3.2.5 on 2021-11-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='asd', max_length=255, verbose_name='password'),
            preserve_default=False,
        ),
    ]
