# Generated by Django 3.2.5 on 2022-03-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eve',
            fields=[
                ('typeId', models.IntegerField(primary_key=True, serialize=False)),
                ('groupId', models.IntegerField()),
                ('typeName', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('mass', models.FloatField()),
                ('volume', models.FloatField()),
                ('capacity', models.FloatField()),
                ('portionsize', models.IntegerField()),
                ('raceId', models.IntegerField()),
                ('basePrice', models.DecimalField(decimal_places=4, max_digits=19)),
                ('published', models.IntegerField()),
                ('marketGroupId', models.IntegerField()),
                ('iconId', models.IntegerField()),
                ('soundId', models.IntegerField()),
                ('graphicId', models.IntegerField()),
            ],
            options={
                'db_table': 'invTypes',
                'managed': False,
            },
        ),
    ]
