# Generated by Django 3.2.5 on 2022-04-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve', '0002_auto_20220410_2314'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ramactivity',
            table='ramAtivities',
        ),
        migrations.AlterModelTable(
            name='solarsystem',
            table='mapSolarSystems',
        ),
    ]
