# Generated by Django 3.2.5 on 2022-04-10 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eve', '0003_auto_20220410_2322'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ramactivity',
            table='ramActivities',
        ),
    ]
